# Module: NumPy Assignments
## Lesson: NumPy

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [10]:
import numpy as np

arr = np.arange(1,26)
arr = arr.reshape(5,5)
print(arr)
arr[0:,3:] = 1
print(arr)

arr2 = np.zeros((4,4))
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  1  1]
 [ 6  7  8  1  1]
 [11 12 13  1  1]
 [16 17 18  1  1]
 [21 22 23  1  1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [11]:
arr = np.arange(1,37)
arr = arr.reshape(6,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [26]:
import random
arr = np.ones((3,4),)
for i in range(len(arr)):
    for j in range(len(arr[i])):
        arr[i][j] = random.randint(1,12)
arr

array([[ 2.,  8.,  1., 10.],
       [ 7., 10.,  1.,  1.],
       [ 3.,  5.,  5.,  7.]])

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [44]:
import random
arr = np.empty((5,5))
for i in range(len(arr)):
    for j in range(len(arr[i])):
        arr[i][j] = random.randint(1,25)
print(arr.mean())  #mean
print(arr.std())   #standard deviation
print(arr.var())    # variance

arr2 = np.array([x for x in range(1,10)]).reshape(3,3)
mini = int(arr2.min())
maxi = int(arr2.max())
normalized_arr = np.empty((3,3))
for i in range(len(arr2)):
    for j in range(len(arr2[i])):
        normalized_arr[i][j] = (arr2[i][j]-mini)/(maxi-mini)

normalized_arr

11.92
8.64832931842908
74.79360000000001


array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [47]:
## 1
arr = np.array([random.randint(1,9) for x in range(9)]).reshape(3,3)
arr2 = np.array([ x for x in range(3)])
print(arr2)
print(arr)
print(arr+arr2)



[0 1 2]
[[3 5 3]
 [4 8 7]
 [6 6 1]]
[[3 6 5]
 [4 9 9]
 [6 7 3]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.