### Numpy

In [1]:
import numpy as np

In [6]:
# To create a 1-D array
arr1 = np.array([1,2,3,4,5]) # We can give list or tuple
print(arr1)
print(type(arr1))
print(arr1.shape) # 1-D with 5 element array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [10]:
# To reshape it to 2-D array
arr2 = arr1.reshape(1,5) # one row and 5 columms
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


In [ ]:
arr2 = np.array([[1,2,3,4,5]]) # 2D array with one row
print(arr2.shape) # 1 row with 5 columns
print(arr2)

(1, 5)
[[1 2 3 4 5]]


In [ ]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # 2 D array with 2 row
print(arr3)
print(arr3.shape) # 2 rows and 5 columns

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [20]:
# Create array using inbuild functions

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [25]:
# To create a array to one

print(np.ones((3,5))) #row col array to ones
print()
print(np.ones((3))) #for one value it takes it for col

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[1. 1. 1.]


In [27]:
# To create a identity matrice
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# To see number of dimensions of array

np.array([[1,2,3]]).ndim

2

In [29]:
# To see number of elements 
np.arange(0,10).size

10

In [31]:
# To see data type of elements or array
print(np.array(['a','b','c']).dtype)
print(np.array([1,2,3,4]).dtype)

<U1
int64


In [36]:
# To see item size in bytes
np.array([1,2,3,4,5,6]).itemsize

8

In [39]:
## Numpy Vectorization Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise operation

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr2/arr1)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [41]:
## Universal functions on numpy array- eleemnt wise

arr = np.array([1,2,3,4,5])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [51]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr[0][0])
print(arr[1])
print(arr[1:,2:])
print(arr[:2,2:])
print(arr[1:,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[5 6 7 8]
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [54]:
arr[0,0] = 100
print(arr)
arr[0,0] = 1

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [55]:
arr[1:] = 100
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]
